version: "3.9"

services:
  core_controller:
    container_name: core_controller
    env_file:
      - ./CoreController/.env
    build:
      context: ./CoreController # Путь до папки с Dockerfile для бэкенда
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - ASPNETCORE_URLS=http://localhost:5001
